name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DOCKER_BUILDKIT: 1
  CONTAINER_REGISTRY: ${{ vars.CONTAINER_REGISTRY}}
  CONTAINER_IMAGE: ${{ vars.CONTAINER_REGISTRY }}/${{ github.repository }}
  DOCKERFILE: Dockerfile
  
jobs:
  hadolint:
    name: Run hadolint scanning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ${{ env.DOCKERFILE }}
          format: sarif
          output-file: hadolint-results.sarif
          failure-threshold: error

      - name: Upload analysys results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: hadolint-results.sarif
          wait-for-processing: true

  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry as user
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: github.actor != 'github-actions[bot]' && github.actor != 'dependabot[bot]' 

      - name: Log in to GitHub Container Registry as Dependabot
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_APP_ID }}
          password: ${{ secrets.GH_APP_DEPENDABOT_PRIVATE_KEY }}
        if: github.actor == 'github-actions[bot]' || github.actor == 'dependabot[bot]'
      
      - name: Set Docker image tag
        run: |
          TAG=$(date +%Y.%m%d.%H%M%S)
          echo "TAG=$TAG" >> "$GITHUB_ENV"
      
      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64, linux/arm64
          file: ${{ env.DOCKERFILE }}
          push: true
          tags: |
            ${{ env.CONTAINER_IMAGE }}-dev:${{ env.TAG }}
        if: github.ref != 'refs/heads/main'

      - name: Scan Docker image with trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ env.CONTAINER_IMAGE }}-dev:${{ env.TAG }}'
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH,MEDIUM'
          format: 'table'
          exit-code: '0'
        if: github.ref != 'refs/heads/main'

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64, linux/arm64
          file: ${{ env.DOCKERFILE }}
          push: true
          tags: |
            ${{ env.CONTAINER_IMAGE }}:${{ env.TAG }}
            ${{ env.CONTAINER_IMAGE }}:latest
        if: github.ref == 'refs/heads/main'


      - name: Scan Docker image with trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ env.CONTAINER_IMAGE }}:${{ env.TAG }}'
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH,MEDIUM'
          format: 'sarif'
          output: 'trivy-results-image.sarif'
          exit-code: '0'
        if: github.ref == 'refs/heads/main'

      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results-image.sarif'
        if: github.ref == 'refs/heads/main'