name: Build and Push Docker Image

on:
  workflow_dispatch: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DOCKER_BUILDKIT: 1
  CONTAINER_REGISTRY: ${{ vars.CONTAINER_REGISTRY}}
  CONTAINER_IMAGE: ${{ vars.CONTAINER_REGISTRY }}/${{ github.repository }}
  DOCKERFILE: ${{ github.workspace }}/Dockerfile
  

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Run hadolint
        uses: hadolint/hadolint@v3.1.0
        with:
          dockerfile: Dockerfile
          failure-theshold: error

      - name: Set Docker image tag
        run: |
          TAG=$(date +%Y.%m%d.%H%M%S)
          echo "TAG=$TAG" >> "$GITHUB_ENV"
          echo "IMAGE_REF=ghcr.io/$GITHUB_REPOSITORY:${TAG}" >> "$GITHUB_ENV"
      
      # - name: Build Docker image
        # run: docker build . -f ${{ env.DOCKERFILE }} -t ${{ env.CONTAINER_IMAGE }}:${{ env.TAG }} -t ${{ env.CONTAINER_IMAGE }}:latest --progress=plain

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64, linux/arm64
          file: ${{ env.DOCKERFILE }}
          push: false
          tags: |
            ${{ env.CONTAINER_IMAGE }}:${{ env.TAG }}

      - name: Scan Docker image with trivy
        uses: aquasecurity/trivy-action@master
        with:
          # image-ref: '${{ env.IMAGE_REF }}'
          image-ref: '${{ env.CONTAINER_IMAGE }}:${{ env.TAG }}'
          # format: 'table'
          exit-code: '1'
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH,MEDIUM'
          format: 'sarif'
          # template: '@contrib/sarif.tpl'
          output: 'trivy-results-image.sarif'
          # test

      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results-image.sarif'

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Push Docker image to GitHub Container Registry
        # run: |
          # IMAGE_TAG="ghcr.io/$GITHUB_REPOSITORY:${{ env.TAG }}"
          # docker push $IMAGE_TAG
          # docker push ghcr.io/$GITHUB_REPOSITORY:latest

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64, linux/arm64
          file: ${{ env.DOCKERFILE }}
          push: true
          tags: |
            ${{ env.CONTAINER_REGISTRY }}/${{ env.CONTAINER_IMAGE }}:${{ env.TAG }}
            ${{ env.CONTAINER_REGISTRY }}/${{ env.CONTAINER_IMAGE }}:latest