name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    types: [ closed ]
    branches:
      - main

env:
  DOCKER_BUILDKIT: 1

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: main
      
      - name: Set Docker image tag
        run: |
          TAG=$(date +%y%m%d.%H%M%S)
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build -t ghcr.io/$GITHUB_REPOSITORY:${{ env.TAG }} -t ghcr.io/$GITHUB_REPOSITORY:latest --progress=plain .

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image to GitHub Container Registry
        run: |
          IMAGE_TAG="ghcr.io/$GITHUB_REPOSITORY:${{ env.TAG }}"
          docker push $IMAGE_TAG
          docker push ghcr.io/$GITHUB_REPOSITORY:latest

      - name: Scan Docker image with trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ghcr.io/nikolaai/fuzzy-engine:${{ env.TAG }}
          # format: 'table'
          # exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          format: 'sarif'
          output: 'trivy-results-image.sarif'

      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: trivy-results-image.sarif

      